displayName=Pump Coker Alert
author=MeatballAWM
description=Alerts when the pump furnace is low on coke.
tags=pump,coker,alert
plugins=PumpCokerAlert.PumpCokerAlertPlugin
version=1.0.0
build=standard
